global:
  scrape_interval: 15s

rule_files:
  - "alert.rules.yml"

scrape_configs:
  - job_name: 'windows_exporter'
    static_configs:
      - targets: ['localhost:9182']
  - job_name: 'pushgateway'
    static_configs:
      - targets: ['localhost:9091']
