name: DevSecOps Pipeline

on:
  push:
    branches: [main]

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: '18'

      - run: npm install
        working-directory: ./app

      - run: npm test || echo "No tests yet"
        working-directory: ./app

  dependency-scan:
    runs-on: ubuntu-latest
    needs: build-test
    steps:
      - uses: actions/checkout@v3
      - name: Run OWASP Dependency Check
        uses: dependency-check/Dependency-Check_Action@main
        with:
          project: "NodeApp"
          scanPath: "./app"

  dast-scan:
    runs-on: ubuntu-latest
    needs: build-test
    steps:
      - name: Start App
        run: |
          cd ./app
          nohup npm install && npm start &
          sleep 10

      - name: Run OWASP ZAP
        uses: zaproxy/action-baseline@v0.7.0
        with:
          target: 'http://localhost:3000'
